#!/bin/bash

SERVICENAME=atlas-system-agent
DFLT_FILE=/etc/default/atlas-system-agent

if [[ -n "$TRACE" ]]; then
  export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  set -o xtrace
fi
set -o pipefail
set -o errexit

[ -f $DFLT_FILE ] && . $DFLT_FILE

if [ -f $ENV_FILE ] ; then
  . $ENV_FILE
else
  echo $ENV_FILE is not present. Cannot send metrics using atlas-system-agent
  exit 1
fi

exec /usr/local/bin/atlas-system-agent
