name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/atlas-system-agent' }}
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: "cmake-build"
      CC: "gcc-11"
      CXX: "g++-11"
      LANG: "en_US.UTF-8"
    strategy:
      matrix:
        agent: [system, titus]
    steps:
      - uses: actions/checkout@v2

      - name: Conan+Cmake Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan
            ~/work/atlas-system-agent/atlas-system-agent/cmake-build
          key: ${{ runner.os }}-conan-cmake

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-11 libcap-dev libiberty-dev

          echo "==== cmake ===="
          cmake -version

          echo "==== python ===="
          python3 -V

          echo "==== conan ===="
          pip install "conan==1.59.0"
          conan --version
          if [[ ! -f ~/.conan/profiles/default ]]; then conan profile new default --detect; fi
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install Project Dependencies
        run: |
          conan install . --build=missing --install-folder $BUILD_DIR
          conan source .

      - name: Build atlas-system-agent
        if: ${{ startsWith(matrix.agent, 'system') }}
        run: |
          cd $BUILD_DIR
          cmake -DCMAKE_BUILD_TYPE=Release -DTITUS_SYSTEM_SERVICE=OFF ..
          cmake --build .
          echo "==== ldd ===="
          ldd bin/atlas_system_agent || true

      - name: Test atlas-system-agent
        if: ${{ startsWith(matrix.agent, 'system') }}
        run: |
          cd $BUILD_DIR
          GTEST_COLOR=1 ctest --verbose

      - name: Build atlas-titus-agent
        if: ${{ startsWith(matrix.agent, 'titus') }}
        run: |
          cd $BUILD_DIR
          cmake -DCMAKE_BUILD_TYPE=Release -DTITUS_SYSTEM_SERVICE=ON ..
          cmake --build .
          echo "==== ldd ===="
          ldd bin/atlas_system_agent || true

      - name: Test atlas-titus-agent
        if: ${{ startsWith(matrix.agent, 'titus') }}
        run: |
          cd $BUILD_DIR
          GTEST_COLOR=1 ctest --verbose