name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/atlas-system-agent' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [system, titus]
    steps:
      - uses: actions/checkout@v4

      - name: Restore Conan Cache
        id: conan-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /home/runner/.conan2
            /home/runner/work/atlas-system-agent/atlas-system-agent/cmake-build
            /home/runner/work/atlas-system-agent/atlas-system-agent/lib/spectator
            /home/runner/work/atlas-system-agent/atlas-system-agent/lib/tools
          key: ${{ runner.os }}-conan

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-13 libcap-dev libiberty-dev

      - name: Build atlas-system-agent
        if: ${{ startsWith(matrix.agent, 'system') }}
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          TITUS_SYSTEM_SERVICE=OFF ./build.sh

      - name: Build atlas-titus-agent
        if: ${{ startsWith(matrix.agent, 'titus') }}
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          TITUS_SYSTEM_SERVICE=ON ./build.sh

      - name: Save Conan Cache
        id: conan-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /home/runner/.conan2
            /home/runner/work/atlas-system-agent/atlas-system-agent/cmake-build
            /home/runner/work/atlas-system-agent/atlas-system-agent/lib/spectator
            /home/runner/work/atlas-system-agent/atlas-system-agent/lib/tools
          key: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}
