name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/atlas-system-agent' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [system, titus, k8s]
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-15 libiberty-dev libdrm-dev

      - name: Build atlas-${{ matrix.agent }}-agent
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          AGENT_FLAVOR=${{ matrix.agent }} ./build.sh
