name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/atlas-system-agent' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [system, titus]
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-13 libcap-dev libiberty-dev

      - name: Build atlas-system-agent
        if: ${{ startsWith(matrix.agent, 'system') }}
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          TITUS_SYSTEM_SERVICE=OFF ./build.sh

      - name: Build atlas-titus-agent
        if: ${{ startsWith(matrix.agent, 'titus') }}
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          TITUS_SYSTEM_SERVICE=ON ./build.sh
